version: '3.8'

services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookDb?serverTimeZone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=13572468TRee@@
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=validate
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_OPEN-IN-VIEW=false
      - SPRING_JACKSON_DESERIALIZATION_FAIL-ON-UNKNOWN-PROPERTIES=true
      - SERVER_SERVLET_CONTEXT-PATH=/api
      - JWT_EXPIRATION=300000
      - JWT_SECRET=secretiveness123456456789878787878787

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 13572468TRee@@
      MYSQL_DATABASE: bookDb